version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=sequelize
      - MYSQL_ROOT_PASSWORD=elpepe
      - MYSQL_PORT=3307
    ports:
      - 3307:3306
    volumes:
    - ./mysql_data:/var/lib/mysql